[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"


[project]
name = "meteocli"
version = "0.1.0"
description = "CLI meteo per terminale (Raspberry/SSH) con grafici ASCII"
readme = "README.md"
authors = [{name = "Snorry0"}]
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
"requests>=2.31",
"rich>=13",
"plotext>=5",
"typer>=0.12.5",
]


[project.scripts]
meteo = "meteocli.cli:main"


[tool.hatch.build.targets.wheel]
packages = ["src/meteocli"]


[tool.ruff]
line-length = 100


[tool.black]
line-length = 100
